## Refer to http://caffe.berkeleyvision.org/installation.html
## NOTE: We're currently using the cmake method rather than this file.
CUDA_DIR := /ad/eng/opt/64/cuda/cuda-6.0
CUDA_ARCH := -gencode arch=compute_20,code=sm_20 \
		-gencode arch=compute_20,code=sm_21 \
		-gencode arch=compute_30,code=sm_30 \
		-gencode arch=compute_35,code=sm_35 \
		-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_50,code=compute_50
BLAS := openblas
BUILD_DIR := build
DISTRIBUTE_DIR := distribute
TEST_GPUID := 0
Q ?= @
INCLUDE_DIRS := /usr/include/openblas

BUILD_matlab := ON
Matlab_mex := /ad/eng/bin/mex
Matlab_mexext := /ad/eng/bin/mexext
CMAKE_INSTALL_PREFIX := /ad/eng/support/software/linux/opt/64/caffe-rc3
PYTHON_INCLUDE_DIR := /ad/eng/opt/64/anaconda/include/python2.7
PYTHON_LIBRARY := /ad/eng/opt/64/anaconda/lib/libpython2.7.so
